### ISSUE TITLE
ICM: Add check to `send` functions

### ISSUE THREAD

**Issue by Nuttymoon** [suzaku-network/suzaku-contracts-library#13]
![image](https://github.com/user-attachments/assets/cd34ce76-76ab-456a-ad77-5180e628d196)

**Comment by Nuttymoon** [comment]
To satisfy [EEA EthTrust Security Level [S]](https://entethalliance.github.io/eta-registry/security-levels-spec.html#sec-levels-one), code that makes external calls using the Low-level Call Functions (i.e. call, delegatecall, staticcall, send, and transfer) MUST check the returned value from each usage to determine whether the call failed. Normally, exceptions in subcalls 'bubble up', unless they are handled in a try/catch. However, Solidity defines a set of Low-level Call Functions that do not have built in safety checks: call, delegatecall, staticcall, send, and transfer. Calls using these functions behave differently. Specifically, they return a boolean indicating whether the call completed successfully. Not explicitly testing the return values of these calls for failure may lead to unexpected behavior in the caller contract.

Within AvalancheICTTRouter.sol, there are calls with missing failure checks. For instance:

- The call [IERC20TokenTransferrer(bridgeHome).send(input, bridgeAmount)](https://github.com/suzaku-network/suzaku-contracts-library/blob/7bd4b78434bd5754ae7fa50bf4486c5da3225a02/contracts/src/contracts/Teleporter/AvalancheICTTRouter.sol#L269) within the contract AvalancheICTTRouter.

- The call [INativeTokenTransferrer(bridgeHome).send{value: bridgeAmount}(input)](https://github.com/suzaku-network/suzaku-contracts-library/blob/7bd4b78434bd5754ae7fa50bf4486c5da3225a02/contracts/src/contracts/Teleporter/AvalancheICTTRouter.sol#L322) within the contract AvalancheICTTRouter.

**Comment by Al3xGROS** [comment]
I don't understand. In our case, the `send` function is not a low-level call function so I don't know what supplementary check I should do.
