### ISSUE TITLE
ICTT: `registerDestinationTokenBridge` does not allow destination chain to be the current chain

### ISSUE THREAD

**Issue by Nuttymoon** [suzaku-network/suzaku-contracts-library#20]
See `issue #02` of the audit report.

**Comment by Nuttymoon** [comment]
I see two options here:
1. We remove the `destinationChainID == routerChainID` if-statement in `registerDestinationTokenBridge` as recommended.  
  @Al3xGROS do we agree that the multi-hop logic happens at the `bridgeSource` level? Meaning that it knows whether to do a multi-hop or not?
2. We acknowledge the issue, saying that the `Router` is intended to bridge to other chains only because it only relies on canonical bridges and one token can only have one canonical bridge per chain.

**Comment by Al3xGROS** [comment]
Let's acknowledge this issue.
