### ISSUE TITLE
ICTT: Router assumes that a token will have only one remote bridge contract per chain

### ISSUE THREAD

**Issue by Nuttymoon** [suzaku-network/suzaku-contracts-library#23]
See `issue #05` of the audit report.

**Comment by Nuttymoon** [comment]
I think we can acknowledge this issue by saying that the `Router` is intended to work with canonical contracts only.

IMO "having a native and an ERC20 version of the token" doesn't make sense. If the token is the native token on the destination chain, we can just use a wrapper contract to transform it to ERC20.

**Comment by Al3xGROS** [comment]
Yes.
